### ISSUE TITLE
select queries aren't sent to multiple configured remote_write destinations

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/prometheus-benchmark#1]
It looks like the benchmark is able to send select queries only to the first configured remote_write destination. If multiple destinations are configured, then others don't receive select queries. This should be fixed.

**Comment by valyala** [comment]
cc @f41gh7

**Comment by hagen1778** [comment]
This would require running multiple vmalert instances. Do you think this would be ok?

**Comment by valyala** [comment]
This issue has been resolved in https://github.com/f41gh7/rw-benchmark/commit/9417b2c16e5666d2847aad2ed0e0b0694c431adc . Closing the issue.
